In [4]:
import numpy as np #with numpy
#previous solution - matrix is old solution, no longer recommended
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[11,12],[13,14],[15,16]])
print("adding:\n", x+y)
print("substraction: \n", x-y)
xx=np.array([[2, 1, 3], [-1, 2, 4]])
yy=np.array([[1, 3], [2, -2], [-1,4]])
print("multiplication: \n", xx@yy)
print("transpose: \n", np.transpose(x))

adding:
 [[12 14]
 [16 18]
 [20 22]]
substraction: 
 [[-10 -10]
 [-10 -10]
 [-10 -10]]
multiplication: 
 [[ 1 16]
 [-1  9]]
transpose: 
 [[1 3 5]
 [2 4 6]]


In [3]:
#the middle-long version, without numpy:
#rowsa=len(a), columnsa=len(a[0])
def adding(a, b):
    if(len(a)==len(b) and len(a[0])==len(b[0])): 
        return[[a[i][j]+b[i][j] for j in range(len(a[0]))] for i in range(len(a))]
    else:
        print("Wrong dimensions.")
    
def subtraction(a, b):
    if(len(a)==len(b) and len(a[0])==len(b[0])):
        return[[a[i][j]-b[i][j] for j in range(len(a[0]))] for i in range(len(a))]
    else:
        print("Wrong dimensions.")
    
def multiplication(a,b):
    if type(a)==int: #with a as a scalar
        return[[a*b[i][j] for j in range(len(b[0]))] for i in range(len(b))]
    elif len(a[0])==len(b):
        rowsa, rowsb=len(a), len(b)
        columnsa, columnsb=len(a[0]), len(b[0])
        zipb=list(zip(*b)) #columns vs rows switching
        return [[ sum(ela * elb for ela, elb in zip(rowsa, columnsb)) for columnsb in zipb] for rowsa in a]
    else:
        print("Wrong dimensions.")
        
def transpose(a):
    mat_tr=[[a[j][i] for j in range(len(a))] for i in range(len(a[0]))]
    return [row for row in mat_tr]
        
def transpose_zip(a):
    return [list(i) for i in zip(*a)]

    
x = [[1,2],[3,4],[5,6]]
y = [[11,12],[13,14],[15,16]]

num=3
xx=[[2, 1, 3], [-1, 2, 4]]
yy=[[1, 3], [2, -2], [-1,4]]

print("adding: ", adding(x,y))
print("subtraction: ", subtraction(x,y))
print("multiplication with a as a scalar: ", multiplication(num, x))
print("multiplication of two matrices: ", multiplication(xx,yy))
print("transpose:", transpose(x))
print("transpose with zip function:", transpose_zip(x))

adding:  [[12, 14], [16, 18], [20, 22]]
subtraction:  [[-10, -10], [-10, -10], [-10, -10]]
multiplication with a as a scalar:  [[3, 6], [9, 12], [15, 18]]
multiplication of two matrices:  [[1, 16], [-1, 9]]
transpose: [[1, 3, 5], [2, 4, 6]]
transpose with zip function: [[1, 3, 5], [2, 4, 6]]


In [3]:
#the longest versions:
def adding(a,b, sign): #also subtraction (through sign="-")
    if(len(a)==len(b) and len(a[0])==len(b[0])):
        rows=len(a)
        columns=len(a[0])
        new=[]
        for i in range(rows):
            row=[]
            for j in range(columns):
                if sign=='+':
                    row.append(a[i][j]+b[i][j])
                elif sign=='-':
                    row.append(a[i][j]-b[i][j])
            new.append(row)
        return new
    else:
        print("Wrong dimensions")
        
def multiplication(a,b):
    if type(a)==int: #with a as a scalar
        new=[]
        rows=len(b)
        columns=len(b[0])
        for i in range(rows):
            row=[]
            for j in range(columns):
                row.append(b[i][j]*a)
            new.append(row)
        return new
    elif len(a[0])==len(b): #multiplication between two matrixes, type(a)==list
        rowsa, rowsb=len(a), len(b)
        columnsa, columnsb=len(a[0]), len(b[0])
        zipb=list(zip(*b)) #columns vs rows switching
        return [[ sum(ela * elb for ela, elb in zip(rowsa, columnsb)) for columnsb in zipb] for rowsa in a]
    else:
        print("Wrong dimensions")
        
x = [[1,2],[3,4],[5,6]]
y = [[11,12],[13,14],[15,16]]

xx=[[2, 1, 3], [-1, 2, 4]]
yy=[[1, 3], [2, -2], [-1,4]]
num=3

print("adding: ", adding(x,y,'+'))
print("subtraction: ", adding(x,y,'-'))
print("multiplication with a as a scalar: ", multiplication(num, x))
print("multiplication of two matrices: ", multiplication(xx,yy))

adding:  [[12, 14], [16, 18], [20, 22]]
subtraction:  [[-10, -10], [-10, -10], [-10, -10]]
multiplication with a as a scalar:  [[3, 6], [9, 12], [15, 18]]
multiplication of two matrices:  [[1, 16], [-1, 9]]
